### PR TITLE
Fix SquashFS extraction when it contains directory symlinks

### LINKED ISSUE #3084: Error while building from image: "failed to create symlink /image/rootfs/var/tmp"
**Version of Singularity**

singularity-ce version 4.1.4-jammy

**Describe the bug**

I cannot use a (certain class of) images to build from. In particular I need to encrypt existing containers for use in sensitive environments. I cannot recreate the existing container, i.e. I need to use the image file.

However the build fails with
```
FATAL:   While performing build: packer failed to pack: root filesystem extraction failed: extract command failed:
[some "WARNING:" lines]

create_inode: failed to create symlink /image/rootfs/var/tmp, because File exists
```

**To Reproduce**

Intended command is: `singularity build --pem-path=/keys/image.pub output.img input.img`, but any build fails:

- `wget -O input.img https://depot.galaxyproject.org/singularity/pigz%3A2.3.4`
- `sudo singularity build --sandbox /tmp/img input.img`

**Expected behavior**

Encrypted image (or sandbox folder) is created

**OS / Linux Distribution**

Which Linux distribution are you using? Is it up-to-date?

Linux Mint 21.3 (Ubuntu 22.04 "jammy") fully patched

**Installation Method**

DEB from GitHub: `singularity-ce_4.1.4-jammy_amd64.deb`

**Additional context**

[Log with --debug](https://github.com/user-attachments/files/16125457/debug.txt)

Console output
```
INFO:    Starting build...
FATAL:   While performing build: packer failed to pack: root filesystem extraction failed: extract command failed: WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /var/lib/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /var/lib/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /var/lib/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container

create_inode: failed to create symlink /image/rootfs/var/tmp, because File exists
Parallel unsquashfs: Using 4 processors
391 inodes (635 blocks) to write

[==============================================================| ] 634/635  99%

created 109 files
created 54 directories
created 281 symlinks
created 0 devices
created 0 fifos
created 0 sockets
: exit status 2
```

### PR DESCRIPTION
**Pull request by cyanezstange**
## Description of the Pull Request (PR):

A SquashFS image might contain directory symlinks such as `/var/tmp -> /tmp`. Before extraction a base environment is created (`makeBaseEnv`) by pre-creating some directories. Among them `/var/tmp`. Although unsquashfs is called with `-force` it fails to replace that by the symlink in the image as it removes only directories.

As per suggestion from @dtrudg the base environment causing the trouble is created after the extraction as done for e.g. OCI images.

### This fixes or addresses the following GitHub issues:

 - Fixes #3084

### CODE REVIEW

File: internal/pkg/build/sources/conveyorPacker_local_test.go [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+	"testing"
+
+	"github.com/sylabs/singularity/v4/internal/pkg/build/sources"
+	"github.com/sylabs/singularity/v4/internal/pkg/image/packer"
+	"github.com/sylabs/singularity/v4/internal/pkg/util/fs"
+	"github.com/sylabs/singularity/v4/pkg/build/types"
+)
+
+func createArchiveFromDir(dir string, t *testing.T) *os.File {
+	mk, err := exec.LookPath("mksquashfs")
```
Comment (dtrudg) [inline internal/pkg/build/sources/conveyorPacker_local_test.go:22]: require.Command(t, "mksquashfs")

File: CHANGELOG.md [hunk 2]
```diff
@@ -40,6 +40,8 @@
   (`docker://`) etc.
 - Fix confusing error messages / incorrect fall-back attempt when explicit
   execution of an OCI-SIF fails.
+- Fix failing build process when building from an image that has symbolic
```
Comment (dtrudg) [inline CHANGELOG.md:43]: This needs to be a bit more specific. Something like...

> Fix failing builds from local images that have symbolic links for paths that are part of the base container environment (e.g. `/var/tmp` -> `/tmp`).

**Review by dtrudg — APPROVED** [review]
Looks good to me, with a minor change required to `CHANGELOG.md` please.

Let's discuss how to squash it... and work through that together.

File: internal/pkg/build/sources/conveyorPacker_local_test.go [hunk 3]
```diff
@@ -0,0 +1,128 @@
...
+	}
+	if err := os.Mkdir(filepath.Join(rootfs, "var"), 0o755); err != nil {
+		t.Fatalf("while creating directory: %v", err)
+	}
+
+	// Create symlinks: /var/tmp -> /tmp , /var/log -> /tmp
+	if err := os.Symlink(filepath.Join(rootfs, "tmp"), filepath.Join(rootfs, "var", "tmp")); err != nil {
+		t.Fatalf("while creating symlink: %v", err)
+	}
+	if err := os.Symlink(filepath.Join(rootfs, "tmp"), filepath.Join(rootfs, "var", "log")); err != nil {
```
Comment (Flamefire) [inline internal/pkg/build/sources/conveyorPacker_local_test.go:48]: `rootfs` is an absolute path to somewhere on the temporary folder, isn't it? I'd suggest to use the original one with `../tmp` to match the original issue or `/tmp` directly to match the comment.
```suggestion
	if err := os.Symlink(filepath.Join("..", "tmp"), filepath.Join(rootfs, "var", "tmp")); err != nil {
		t.Fatalf("while creating symlink: %v", err)
	}
	if err := os.Symlink(filepath.Join("..", "tmp"), filepath.Join(rootfs, "var", "log")); err != nil {
```

Comment (cyanezstange) [reply internal/pkg/build/sources/conveyorPacker_local_test.go:48]: Hi, thank you very much for the review and pointing out this issue. I'll check it soon.

**Comment by cyanezstange** [comment]
Changed targets for unit test symlinks as suggested by @Flamefire . Links now point to a proper directory as expected.
There is an e2e test that fails due to a Docker rate-limit, what's your suggestion on this @dtrudg ?

**Review by Flamefire — APPROVED** [review]

**Comment by dtrudg** [comment]
> Changed targets for unit test symlinks as suggested by @Flamefire . Links now point to a proper directory as expected. There is an e2e test that fails due to a Docker rate-limit, what's your suggestion on this @dtrudg ?

So - really it doesn't matter where the symlink points. The issue is just caused by a symlink being present. Using `<rootfs>/tmp` does give a 'broken' symlink in the container, but this will still cause the issue to present itself.

It's fine to use the relative symlink, or absolute symlink though. We aren't doing anything here which is problematic.

I've re-triggered the failing test. If it passes then this is good to merge.
