### PR TITLE
fix: Don't truncate config file until we have valid output to write

### LINKED ISSUE #409: Empty singularity.conf from invalid set
**Version of Singularity**

master

**Describe the bug**

E2E has been sporadically throwing errors in SEQ/CONFIG where `cryptsetup path` appears unset. With some instrumentation, this is isolated to where it is run after `SEQ/PULL/ordered/concurrencyConfig`.

`/usr/local/bin/singularity config global --set download concurrency -1` is resulting in an empty e2e `singularity.conf`, and the next set/reset is producing one with default values (and empty paths).

```
=== RUN   TestE2E/SEQ/PULL/ordered/concurrencyConfig/DownloadConcurrency-set
    concurrency.go:32: Running command "/usr/local/bin/singularity config global --set download concurrency 5"
=== RUN   TestE2E/SEQ/PULL/ordered/concurrencyConfig/DownloadConcurrency-reset
    concurrency.go:41: Running command "/usr/local/bin/singularity config global --reset download concurrency"
=== RUN   TestE2E/SEQ/PULL/ordered/concurrencyConfig/InvalidDownloadConcurrency-set
    concurrency.go:32: Running command "/usr/local/bin/singularity config global --set download concurrency -1"
=== CONT  TestE2E/SEQ/PULL/ordered/concurrencyConfig
    pull.go:676: *** CONFIG IS BROKEN ***
    pull.go:682: 
=== RUN   TestE2E/SEQ/PULL/ordered/concurrencyConfig/InvalidDownloadConcurrency-reset
    concurrency.go:41: Running command "/usr/local/bin/singularity config global --reset download concurrency"
=== CONT  TestE2E/SEQ/PULL/ordered/concurrencyConfig
    pull.go:676: *** CONFIG IS BROKEN ***
    pull.go:682: # SINGULARITY.CONF
        # This is the global configuration file for Singularity. This file controls
        # what the container is allowed to do on a particular host, and as a result
        # this file must be owned by root.
        
```

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

When using `config global --set` an invalid directive value could previously
lead to an empty `singularity.conf`, as the file was opened with
`O_TRUNC` before the new config was generated/validated.

Generate the config output to an in memory buffer, and only create /
truncate the `singularity.conf` file once we have generated known valid
output.

### This fixes or addresses the following GitHub issues:

 - Fixes #409

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

### CODE REVIEW

**Review by EmmEff — APPROVED** [review]

File: internal/app/singularity/config_global_linux.go [hunk 1]
```diff
@@ -38,8 +40,21 @@ func contains(slice []string, val string) bool {
 }
 
 func generateConfig(path string, directives singularityconf.Directives, dry bool) error {
-	out := os.Stdout
+	// Generate the config structure from our directives
+	c, err := singularityconf.GetConfig(directives)
+	if err != nil {
+		return fmt.Errorf("configuration directive invalid: %v", err)
```
Comment (tri-adam) [inline internal/app/singularity/config_global_linux.go:46]:
```suggestion
		return fmt.Errorf("configuration directive invalid: %w", err)
```

File: internal/app/singularity/config_global_linux.go [hunk 2]
```diff
@@ -38,8 +40,21 @@ func contains(slice []string, val string) bool {
...
+	}
+
+	// Write a config file to our in memory buffer
+	newConfig := new(bytes.Buffer)
+	if err := singularityconf.Generate(newConfig, "", c); err != nil {
+		return fmt.Errorf("while generating configuration from template: %s", err)
```
Comment (tri-adam) [inline internal/app/singularity/config_global_linux.go:52]:
```suggestion
		return fmt.Errorf("while generating configuration from template: %w", err)
```

File: internal/app/singularity/config_global_linux.go [hunk 3]
```diff
@@ -52,13 +67,9 @@ func generateConfig(path string, directives singularityconf.Directives, dry bool
...
 
-	c, err := singularityconf.GetConfig(directives)
+	_, err = io.Copy(out, newConfig)
 	if err != nil {
-		return err
-	}
-
-	if err := singularityconf.Generate(out, "", c); err != nil {
-		return fmt.Errorf("while generating configuration from template: %s", err)
+		return fmt.Errorf("while writing configuration file %s: %s", path, err)
```
Comment (tri-adam) [inline internal/app/singularity/config_global_linux.go:72]:
```suggestion
		return fmt.Errorf("while writing configuration file %s: %w", path, err)
```

**Review by tri-adam — APPROVED** [review]
Suggest using wrapped errors. Otherwise, LGTM!
