### PR TITLE
fix: normalize OCI platform arch & variant

### LINKED ISSUE #2039: ARM(64) platform not normalized correctly
**Version of Singularity**

main

**Describe the bug**

With the changes introduced for `--platform` handling when fetching OCI images some e2e-tests fail on arm64:

```
   === RUN   TestE2E/PAR/DOCKER/ordered/permissions
        singularitycmd.go:698: Running command "/usr/bin/singularity build /tmp/stest.1914405190/perm-2582949477/container docker://sylabsio/userperms"
        singularitycmd.go:698:
            "/usr/bin/singularity build /tmp/stest.1914405190/perm-2582949477/container docker://sylabsio/userperms" output:
            INFO:    Starting build...
            FATAL:   While performing build: conveyor failed to get: no image satisfies requested platform: linux/arm64/v8
  
        singularitycmd.go:698: got 255 as exit code and was expecting 0: exit status 255
            waiting for command "/usr/bin/singularity build /tmp/stest.1914405190/perm-2582949477/container docker://sylabsio/userperms"
            github.com/sylabs/singularity/v4/e2e/internal/e2e.TestEnv.RunSingularity.func1
                    github.com/sylabs/singularity/v4/e2e/internal/e2e/singularitycmd.go:673
            github.com/sylabs/singularity/v4/e2e/internal/e2e.TestEnv.RunSingularity.func2
                    github.com/sylabs/singularity/v4/e2e/internal/e2e/singularitycmd.go:698
            runtime.goexit
                    runtime/asm_arm64.s:1197
```

This is because the images for these tests were built and pushed with buildx, resulting in a platform of `linux/arm64`, without the additional `/v8` variant, and we are not accommodating this.

Another related issue is that for ARM32... `arm` is meant to infer `arm/v7` - anything else that a v7 variant has to be specified explicitly.

We need to add normalization for ARM and ARM64:

* `linux/arm64/v8` normalizes to `linux/arm64` before it is used to check compatibility with an image.
* `linux/arm` normalizes to `linux/arm/v7` before it is used to check compatibility with an image.

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

In order to ensure that we can pull the correct image on ARM systems:

* `linux/arm64/v8` needs to be normalized to `linux/arm64`
* `linux/arm` needs to be normalized to `linux/arm/v7`

Bring across a small amount of additional code from containerd/containerd (under a compatible license) to perform the normalization.

### This fixes or addresses the following GitHub issues:

 - Fixes #2039 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

File: internal/pkg/ociplatform/ociplatform_test.go [hunk 1]
```diff
@@ -43,36 +43,62 @@ func Test_sysCtxToPlatform(t *testing.T) {
...
+				OSChoice:           "linux",
+				ArchitectureChoice: "arm64",
+				VariantChoice:      "v8",
+			},
+			want: ggcrv1.Platform{
+				OS:           "linux",
+				Architecture: "arm64",
+				Variant:      "",
+			},
+		},
```
Comment (wobito) [inline internal/pkg/ociplatform/ociplatform_test.go:90]: Would it a good idea to add a case for `aarch64` normalization?
