### PR TITLE
fix: don't flatten layers with ggcr before extracting (4.1)

### LINKED ISSUE #2684: bug: link: unpriv.link: unpriv.wrap target: no such file or directory (ggcr / umoci image extraction)
**Version of Singularity**

main / 4.1

**Describe the bug**

See also: https://github.com/sylabs/singularity/discussions/2675#discussioncomment-8571307

Some layer of the image quay.io/broadsword/recount-unify:1.1.1 contains a link that opencontainers/umoci (used by singularity) is unable to extract:

```
singularity pull docker://quay.io/broadsword/recount-unify:1.1.1
INFO:    Extracting OCI image... FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: unpack entry: opt/conda/pkgs/certifi-2018.11.29-py37_0/lib/python3.7/site-packages/certifi/__init__.py: link: unpriv.link: unpriv.wrap target: no such file or directory
```

Needs to be investigated to find out the nature of this link, so that we can file an issue upstream in umoci, or find some kind of workaround.

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

Pick #2685

The ggcr module has a bug in its `mutate.Extract` function, due to optimisations that do not correctly track hard links that are manipulated in specific ways across layers:

https://github.com/google/go-containerregistry/issues/977

Prior to this PR, we were using `mutate.Extract` to flatten an image so that we were only extracting a single tar into a rootfs with umoci. This meant that the bug above could cause umoci to fail, as the flattened tar is invalid in certain circumstances.

Fix the issue by avoiding `mutate.Extract`. Instead extract each layer, in order, using umoci.

### This fixes or addresses the following GitHub issues:

 - Fixes #2684 (native mode)

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

File: internal/pkg/ociimage/unpack.go [hunk 1]
```diff
@@ -88,15 +85,26 @@ func UnpackRootfs(_ context.Context, srcImage v1.Image, destDir string) (err err
...
+			return fmt.Errorf("while reading layer: %s: %w", layerDigest, err)
+		}
+		unpackOptions := umocilayer.UnpackOptions{MapOptions: mapOptions}
+		err = umocilayer.UnpackLayer(destDir, layerReader, &unpackOptions)
+		if err != nil {
+			return fmt.Errorf("while unpacking layer %s: %w", layerDigest, err)
+		}
+		if err := layerReader.Close(); err != nil {
+			return fmt.Errorf("while closing layer %s: %w", layerDigest, err)
+		}
```
Comment (tri-adam) [inline internal/pkg/ociimage/unpack.go:105]: This should happen even if `umocilayer.UnpackLayer` fails? Might be worth a `defer` after `l.Uncompressed`?

**Review by tri-adam — CHANGES_REQUESTED** [review]

**Review by tri-adam — APPROVED** [review]
