### PR TITLE
e2e: refactor test image handling 

### LINKED ISSUE #1364: e2e: e2e.EnsureOCIImage is not architecture aware
**Version of Singularity**

main

**Describe the bug**

e2e.EnsureOCIImage is always providing an AMD64 image, so any test calling it and operating on the provided image will fail on a non-AMD64 platform.

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

Fetch the OCI archive image used in tests from Docker Hub, so that it will match the host architecture.

### This fixes or addresses the following GitHub issues:

 - Fixes #1364

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

File: e2e/internal/e2e/image.go [hunk 1]
```diff
@@ -206,8 +206,5 @@ func EnsureOCIImage(t *testing.T, env TestEnv) {
 	}
 
 	// Prepare oci-archive source
-	err := DownloadFile(ociArchiveURI, env.OCIImagePath)
-	if err != nil {
-		t.Fatalf("Could not download oci archive test file: %v", err)
-	}
+	CopyOCIImage(t, ociImageURI, "oci-archive:"+env.OCIImagePath, false, false)
```
Comment (dtrudg) [inline e2e/internal/e2e/image.go:209]: Need to use auth here if we have it.

File: e2e/suite.go [hunk 2]
```diff
@@ -219,7 +219,7 @@ func Run(t *testing.T) {
 			t.Fatalf("could not convert E2E_DOCKER_MIRROR_INSECURE=%s: %s", insecureValue, err)
 		}
 	}
-	e2e.CopyOCIImage(t, "busybox:latest", fmt.Sprintf("%s/my-busybox:latest", testenv.TestRegistry), insecureSource, true)
+	e2e.CopyOCIImage(t, "docker://busybox:latest", fmt.Sprintf("docker://%s/my-busybox:latest", testenv.TestRegistry), insecureSource, true)
```
Comment (dtrudg) [inline e2e/suite.go:222]: Need to use auth here if we have it.

**Review by EmmEff — APPROVED** [review]
