### PR TITLE
fix: Remove files with restrictive perms from --oci temp rootfs

### LINKED ISSUE #1586: failure to remove almalinux rootfs in --oci mode
**Version of Singularity**

main

**Describe the bug**

```
$ singularity run --oci docker://almalinux
2023/04/21 10:28:46  info unpack layer: sha256:63c7cbfce3f306a83bb69ed11284ee1fdcd3fdbeec4769e30e03123cd7ced99d
2023/04/21 10:28:46  warn rootless{usr/bin/newgidmap} ignoring (usually) harmless EPERM on setxattr "security.capability"
2023/04/21 10:28:46  warn rootless{usr/bin/newuidmap} ignoring (usually) harmless EPERM on setxattr "security.capability"
2023/04/21 10:28:47  warn rootless{usr/sbin/arping} ignoring (usually) harmless EPERM on setxattr "security.capability"
2023/04/21 10:28:47  warn rootless{usr/sbin/clockdiff} ignoring (usually) harmless EPERM on setxattr "security.capability"
bash-4.4$ exit
ERROR:   Couldn't remove OCI bundle /tmp/oci-bundle1780910701: unlinkat /tmp/oci-bundle1780910701/rootfs/root/.bash_logout: permission denied
dtrudg-sylabs@mini:~
```

This appears to be an `--oci` mode variant of an old issue... https://github.com/apptainer/singularity/issues/5298

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

When we run a container in `--oci` mode, we have a temporary rootfs that must be removed when the container exits.

A container can contain files / dirs with restrictive permissions that prevent direct removal.

Use fs.ForceRemoveAll, which will chmod & remove anything that os.RemoveAll is unable to remove.

### This fixes or addresses the following GitHub issues:

 - Fixes #1586

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

File: e2e/docker/regressions.go [hunk 1]
```diff
@@ -256,3 +257,34 @@ func (c ctx) issue1528(t *testing.T) {
...
+		e2e.WithProfile(e2e.OCIUserProfile),
+		e2e.WithCommand("exec"),
+		e2e.WithArgs("docker://almalinux:9.1-minimal-20230407", "/bin/true"),
+		e2e.WithEnv(append(os.Environ(), "TMPDIR="+tmpDir)),
+		e2e.ExpectExit(0,
+			e2e.ExpectError(e2e.UnwantedContainMatch, "permission denied"),
+		),
+	)
+
+	d, err := os.Open(tmpDir)
```
Comment (preminger) [inline e2e/docker/regressions.go:282]: This is more of a question than a comment, but I wonder what are the pros and cons of putting this code directly in the body of the `issue1586()`, as opposed to wrapping it as an `e2e.PostRun` passed as part of `RunSingularity()`...?

Comment (dtrudg) [reply e2e/docker/regressions.go:282]: I generally prefer not to use `e2e.PostRun` unless it is necessary, just beause I don't really like adding anonymous functions and more nesting / brackets when it's not necessary. It's just a personal preference.

There is a specific, and fairly common, situation where `e2e.PostRun` is required....

Often we are calling `RunSingularity` with `AsSubtest`, so that e.g. when looping over different profiles, each `singularity` executions using a different profile takes place in a different subtest.

The subtest is created within `RunSingularity`, and is not accessible outside... so if we want to do any checks, we must do them, and fail the subtest, we have to do it in `PostRun`, where the `t` passed in is the subtest.
