### PR TITLE
fix: honor hostname in library:// URI for `singularity delete`

### LINKED ISSUE #243: delete does not honor hostname in library URI
**Version of Singularity**

3.8.1

**Describe the bug**

`singularity delete` will accept a library URI with a hostname, e.g. 

```
$ singularity -d delete library://library.example.com/dtrudg-sylabs2/test/test
```

However, the request is made against the current remote.

**Expected behavior**

Specified hostname should be honored.

### PR DESCRIPTION
**Pull request by dtrudg**
`singularity delete` would accept a hostname in the library:// URI
provided, but would perform the request against the default remote.

Fix this, so it is handled in the same way as for push/pull.

### This fixes or addresses the following GitHub issues:

 - Fixes #243 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

### CODE REVIEW

File: cmd/internal/cli/delete.go [hunk 1]
```diff
@@ -97,6 +97,14 @@ var deleteImageCmd = &cobra.Command{
 			sylog.Fatalf("Error parsing library ref: %v", err)
 		}
 
+		var libraryURI string
+		if deleteLibraryURI != "" {
+			libraryURI = deleteLibraryURI
+		} else if imageRef.Host != "" {
+			// override libraryURI if ref contains host name
+			libraryURI = "https://" + imageRef.Host
```
Comment (tri-adam) [inline cmd/internal/cli/delete.go:105]: I'm not sure what should happen if someone supplies `--library` as well as `library://host/blah`. I'm tempted to say we might want to treat this as an error? If the purpose of the `imageRef` is to (possibly) specify its location, it's confusing if it _doesn't_ delete from the right location because `--library` is set?

**Review by tri-adam — APPROVED** [review]
Looks good, just one question on an edge case, thanks.

File: cmd/internal/cli/delete.go (hunk 1 above)
Comment (dtrudg) [reply cmd/internal/cli/delete.go:105]: Yeah - this is a silly oversight on my part as it's already handled that way for `pull`

Comment (dtrudg) [reply cmd/internal/cli/delete.go:109]: Please see amended code.

**Review by tri-adam — APPROVED** [review]
