### PR TITLE
fix: oci: explicit bind options for /sys /proc sources

### LINKED ISSUE #2069: bug: --nopid in --oci mode fails with runc
**Version of Singularity**

main

**Describe the bug**

Observed on Ubuntu 20.04, 22.04, EL7 with runc

Using `--no-pid` in OCI mode causes an error - operation not permitted when bind mounting `/proc` to `/proc`.

This error does not occur with crun.

```
    === RUN   TestE2E/PAR/ACTIONS/ociExec/OCIFakeroot/NoPID
        oci.go:356: Running command "/usr/bin/singularity exec --oci --fakeroot --no-pid /tmp/stest.1381876698/oci-sif.sif sh -c echo $$"
        oci.go:356:
            "/usr/bin/singularity exec --oci --fakeroot --no-pid /tmp/stest.1381876698/oci-sif.sif sh -c echo $$" output:
            time="2023-08-16T16:58:32Z" level=warning msg="unable to get oom kill count" error="no directory specified for memory.oom_control"
            time="2023-08-16T16:58:32Z" level=warning msg="cannot toggle freezer: cgroups not configured for container"
            time="2023-08-16T16:58:32Z" level=warning msg="cannot toggle freezer: cgroups not configured for container"
            time="2023-08-16T16:58:32Z" level=warning msg="lstat : no such file or directory"
            time="2023-08-16T16:58:32Z" level=error msg="runc run failed: unable to start container process: error during container init: error mounting \"/proc\" to rootfs at \"/proc\": mount /proc:/proc (via /proc/self/fd/6), flags: 0x5026: operation not permitted"
  
        oci.go:356: got 1 as exit code and was expecting 0: exit status 1
            waiting for command "/usr/bin/singularity exec --oci --fakeroot --no-pid /tmp/stest.1381876698/oci-sif.sif sh -c echo $$"
            github.com/sylabs/singularity/v4/e2e/internal/e2e.TestEnv.RunSingularity.func1
                    github.com/sylabs/singularity/v4/e2e/internal/e2e/singularitycmd.go:673
            testing.tRunner
                    testing/testing.go:1595
            runtime.goexit
                    runtime/asm_amd64.s:1650
```

The root cause also results in failures of:

```
TestE2E/PAR/ACTIONS/ociExitSignals/SignalKill/OCIUser
TestE2E/PAR/ACTIONS/ociExitSignals/SignalAbort/OCIUser
```

### LINKED ISSUE #2070: bug: e2e: cgroupfs mount failure in OCI mode with runc
**Version of Singularity**
What version of Singularity are you using? Run:

**Describe the bug**

Seen with Ubuntu 22.04 and runc.

```
--- FAIL: TestE2E/SEQ/CGROUPS/action_flags_rootless_cgroups/rootless/OCIUser (0.78s)
                            --- FAIL: TestE2E/SEQ/CGROUPS/action_flags_rootless_cgroups/rootless/OCIUser/memory (0.22s)
                            --- FAIL: TestE2E/SEQ/CGROUPS/action_flags_rootless_cgroups/rootless/OCIUser/memory-reservation (0.18s)
                            --- FAIL: TestE2E/SEQ/CGROUPS/action_flags_rootless_cgroups/rootless/OCIUser/memory-swap (0.18s)
                            --- FAIL: TestE2E/SEQ/CGROUPS/action_flags_rootless_cgroups/rootless/OCIUser/pids-limit (0.20s)
```

Underlying cause is that the tests attempt to bind the cgroupfs into the container to observe the limits being applied.

This fails with runc (succeeds with crun):

```
    === RUN   TestE2E/SEQ/CGROUPS/action_flags_rootless_cgroups/rootless/OCIUser/memory
        singularitycmd.go:698: Running command "/usr/bin/singularity exec --oci --memory 500M -B /sys/fs/cgroup oci-sif:/tmp/stest.2268700094/oci-sif.sif /bin/sh -c cat /sys/fs/cgroup$(cat /proc/self/cgroup | grep '^0::' | cut -d ':' -f 3)/memory.max"
        singularitycmd.go:698:
            "/usr/bin/singularity exec --oci --memory 500M -B /sys/fs/cgroup oci-sif:/tmp/stest.2268700094/oci-sif.sif /bin/sh -c cat /sys/fs/cgroup$(cat /proc/self/cgroup | grep '^0::' | cut -d ':' -f 3)/memory.max" output:
            time="2023-08-16T17:09:39Z" level=error msg="runc run failed: unable to start container process: error during container init: error mounting \"/sys/fs/cgroup\" to rootfs at \"/sys/fs/cgroup\": mount /proc/self/fd/7:/sys/fs/cgroup (via /proc/self/fd/11), flags: 0x5026: operation not permitted"
  
        singularitycmd.go:698: got 1 as exit code and was expecting 0: exit status 1
            waiting for command "/usr/bin/singularity exec --oci --memory 500M -B /sys/fs/cgroup oci-sif:/tmp/stest.2268700094/oci-sif.sif /bin/sh -c cat /sys/fs/cgroup$(cat /proc/self/cgroup | grep '^0::' | cut -d ':' -f 3)/memory.max"
            github.com/sylabs/singularity/v4/e2e/internal/e2e.TestEnv.RunSingularity.func1
                    github.com/sylabs/singularity/v4/e2e/internal/e2e/singularitycmd.go:673
            github.com/sylabs/singularity/v4/e2e/internal/e2e.TestEnv.RunSingularity.func2
                    github.com/sylabs/singularity/v4/e2e/internal/e2e/singularitycmd.go:698
            runtime.goexit
                    runtime/asm_arm64.s:1197
```

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

When `/sys` or `/proc` are requested to be bind mounted into a container, the bind mount options must be at least as restrictive as on the host.

`/sys` and `/proc` filesystems are generally `nosuid,nodev,noexec`.

`runc` doesn't try more restrictive options on a failed mount, so we have to ensure `nosuid,nodev,noexec` are always set when a bind source is `/sys` or `/proc`.

Tested with `runc` on Fedora - which exhibits the failures shown in the issues.

### This fixes or addresses the following GitHub issues:

 - Fixes #2069 
 - Fixes #2070

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

File: internal/pkg/runtime/launcher/oci/mounts_linux.go [hunk 1]
```diff
@@ -625,13 +625,19 @@ func (l *Launcher) addBindMount(mounts *[]specs.Mount, b bind.Path, allowSUID bo
...
 	}
 
+	// /proc and /sys need nosuid,noexec,nodev set explicitly for runc
+	// See: https://github.com/opencontainers/runc/discussions/3801
 	opts := []string{"rbind", "nodev"}
+	if strings.HasPrefix(b.Source, "/proc") || strings.HasPrefix(b.Source, "/sys") {
+		opts = append(opts, "nosuid", "noexec")
+	} else {
+		if !allowSUID {
+			opts = append(opts, "nosuid")
```
Comment (preminger) [inline internal/pkg/runtime/launcher/oci/mounts_linux.go:635]: This is low priority, but: I don't love the multiple paths of boolean "descent" that can lead to `nosuid`. I think I'd prefer if there was a set(/map) of options, so that adding something like `nosuid` twice would have no ill effects, and then when it's time to build the actual options string, the members of that set are joined with commas. It'd simplify this code and, esp., reading this code, imo.

Comment (dtrudg) [reply internal/pkg/runtime/launcher/oci/mounts_linux.go:635]: I see your point. I think if we are going to simplify in this manner then I'd prefer to have our own struct, wrapping specs.Mount, that provides something like an `.addOptions(...)` function.

If you'd like to take that on that'd be good.

What I don't want to do is add temporary maps, and map <=> slice conversion code inside multiple existing functions.
