### PR TITLE
 fix: cgroups: check for systemd init when needed

### LINKED ISSUE #3536: Singularity-in-docker --oci as root fails
Running SingularityCE inside a docker container, as root in the container fails:

```
docker run -it --rm --privileged singularity:main run --oci docker://alpine
INFO:    Converting layers to SquashFS
INFO:    Cleaning up.
time="2025-02-19T15:04:57Z" level=error msg="runc run failed: systemd not running on this host, cannot use systemd cgroups manager"
```

This is due to runc attempting to use the systemd cgroups manager.

To use systemd, running on the host, then `/run` must be bound in, and `--pid=host` used - the container is then operational:

```
$ docker run -it --rm -v /run:/run --pid=host --privileged singularity:main run --oci docker://alpine
3.5MiB / 3.5MiB [===============================================================================================================================] 100 % 776.4 KiB/s 0s
INFO:    Converting layers to SquashFS
INFO:    Cleaning up.
/ # hostname
12a126ae973e
/ # 
```

It should be possible to run without requiring systemd cgroup creation inside the Docker container.

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

When `CanUseCgroups` is called, with systemd as the intended cgroups manager, make sure that a systemd init is actually running.

This fixes flows where Singularity run nested inside another container, that doesn't provide a systemd init or mount the host `/run` directory into the container.

### This fixes or addresses the following GitHub issues:

 - Fixes #3536

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

File: internal/pkg/cgroups/util.go [hunk 1]
```diff
@@ -117,12 +118,25 @@ func HasXDGRuntimeDir() (bool, error) {
...
 // warn controls whether configuration problems preventing use of cgroups will be logged as warnings, or debug messages.
 func CanUseCgroups(systemd bool, warn bool) bool {
+	if systemd {
+		systemdRunning := fs.IsDir("/run/systemd/system")
+		if !systemdRunning {
+			if warn {
+				sylog.Warningf("Cannot use systemd cgroups manager, systemd not running as init on this host.")
+			} else {
+				sylog.Warningf("Cannot use systemd cgroups manager, systemd not running as init on this host.")
+			}
```
Comment (wobito) [inline internal/pkg/cgroups/util.go:135]: Both cases have exactly the same warning message. That doesn't seem right. 

Or Am I missing something?

**Review by wobito — COMMENTED** [review]
Just a if statement confusion

File: internal/pkg/cgroups/util.go (hunk 1 above)
Comment (wobito) [reply internal/pkg/cgroups/util.go:135]: Based on the comment one should be a debug log

Comment (dtrudg) [reply internal/pkg/cgroups/util.go:135]: :facepalm: meant to be same message, but bottom one Debug.
