### PR TITLE
fix: oci: always use rootless uid for inner uid map

### LINKED ISSUE #2623: oci: container USER is affecting inner uid_map
**Version of Singularity**

main / 4.1

**Describe the bug**

At some point, the `USER` uid, picked up from an image config has started to addect the inner uid_map of OCI-Mode rootless.

The map is being calculated based on the `USER` uid, and not the uid of the person starting the container. This will cause incorrect ownership of files in the container image.

We get:

```
$ singularity shell --oci docker://sylabsio/docker-user
INFO:    Using cached OCI-SIF image
Singularity> cat /proc/self/uid_map
         0          1       2000
      2000          0          1
      2001       2001      63536
Singularity> 
```

We should have:

```
~ $ cat /proc/self/uid_map 
         0          1       1000
      1000          0          1
      1001       1001      64536
```

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

In OCI mode, as an unprivileged user, we have an outer UID/GID mapping from the host UID/GID to 0:0 and an inner UID/GID mapping back to the host UID/GID.

The code was erroneously using the targetUID/GID for the container process rather than the host UID/GID for the inner mapping. This meant that when a container specifying an Dockerfile `USER` was run the mapping and file owneship in the container was incorrect.

Fix the mapping and add e2e-tests that verify correct file ownership for a container with a `USER`.

### This fixes or addresses the following GitHub issues:

 - Fixes #2623

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

File: internal/pkg/runtime/launcher/oci/launcher_linux.go [hunk 1]
```diff
@@ -320,7 +320,7 @@ func (l *Launcher) finalizeSpec(ctx context.Context, b ocibundle.Bundle, spec *s
 	containerUser := false
 
 	// If the OCI image config specifies a USER we will:
-	//  * When unprivileged - run as that user, via nested subuid/gid mappings (host user -> userns root -> OCI USER)
```
Comment (dtrudg) [inline internal/pkg/runtime/launcher/oci/launcher_linux.go:323]: Note - this comment wasn't really incorrect... where the parenthesized portion refers to the effective UID at each stage.

However it's easy to read it as if the parenthesized portion describes the ID mapping.. which may have led to this bug.

**Review by EmmEff — APPROVED** [review]
