### PR TITLE
fix: check remote build bootstrap valid before submitting

### LINKED ISSUE #10: Perform build argument sanity checking
### Version of Singularity:

What version of Singularity are you using?

3.7.2

### Expected behavior

What did you expect to see when you do...?

Error out early if `singularity build --remote` IMAGE PATH contains an invalid scheme in the URI. For example, `libary://...` (instead of `library:/...`)

### Actual behavior

What actually happend? Why was it incorrect?

(Remote) Build was performed and once complete, an error was displayed that IMAGE PATH is invalid.

### Steps to reproduce this behavior

`singularity build -r libary://entity/collection/container:tag`

Note the error in the URI scheme.

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

When we submit a remote build we should check that the 'bootstrap' header is valid before we submit the remote build.

Also ensure it is not a 'localimage' source, as this is not supported at present.

Example...

```
04:51 PM $ singularity build -r test.sif libary://alpine
FATAL:   Unable to build from libary://alpine: invalid build source "libary"
```

### This fixes or addresses the following GitHub issues:

 - Fixes #10

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

### CODE REVIEW

File: cmd/internal/cli/build_linux.go [hunk 1]
```diff
@@ -188,6 +188,14 @@ func runBuildRemote(ctx context.Context, cmd *cobra.Command, dst, spec string) {
 		sylog.Fatalf("Unable to build from %s: %v", spec, err)
 	}
 
+	// Ensure that the definition bootstrap source is valid before we submit a remote build
+	if _, err := build.NewConveyorPacker(def); err != nil {
+		sylog.Fatalf("Unable to build from %s: %v", spec, err)
+	}
+	if def.Header["bootstrap"] == "localimage" {
```
Comment (tri-adam) [inline cmd/internal/cli/build_linux.go:195]: Might be good to be defensive here?

```suggestion
	if bs, ok := def.Header["bootstrap"]; ok && bs == "localimage" {
```

File: internal/pkg/build/conveyorPacker.go [hunk 2]
```diff
@@ -30,8 +30,8 @@ type ConveyorPacker interface {
 	Packer
 }
 
-// conveyorPacker returns a valid ConveyorPacker for the given image definition.
-func conveyorPacker(def types.Definition) (ConveyorPacker, error) {
+// NewConveyorPacker returns a valid ConveyorPacker for the given image definition.
+func NewConveyorPacker(def types.Definition) (ConveyorPacker, error) {
 	switch def.Header["bootstrap"] {
```
Comment (tri-adam) [inline internal/pkg/build/conveyorPacker.go:35]: Same here, might be best to return an `error` if `def.Header["bootstrap"]` isn't defined?

**Review by tri-adam — CHANGES_REQUESTED** [review]
Just a couple of suggestions, thanks!

**Review by tri-adam — APPROVED** [review]
