### PR TITLE
tests: allow for cgroups freeze/thaw that isn't instant

### LINKED ISSUE #565: Failure of TestCgroupsV1/systemd/FreezeThaw in CI
**Version of Singularity**

master branch

**Describe the bug**

CI failed with:

```
=== RUN   TestCgroupsV1/systemd/FreezeThaw
    manager_linux_test.go:168: Creating test process
    manager_linux_test.go:185: No hugetlb.2MB.max - using alternate cgroups test file
    manager_linux_test.go:160: Process 38420 had state "R", expected state "D"
```

This passed in several runs on the PR. Needs to be looked into as an intermittent failure.

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

Freezing a cgroup is almost always instant for our trivial test cases... except when it isn't due to system load, slow qemu emulation of alternate architectures etc.

The Linux docs explicitly show this in their example :-)

    to freeze all tasks in the container :
       # echo FROZEN > /sys/fs/cgroup/freezer/0/freezer.state
       # cat /sys/fs/cgroup/freezer/0/freezer.state
       FREEZING
       # cat /sys/fs/cgroup/freezer/0/freezer.state
       FROZEN

Allow up to 5 retries, separated by 1 second for processes to be suspended in our tests.

Verified by running the tests in a hard loop on a loaded and slow constrained system, and observing behaviour.

### This fixes or addresses the following GitHub issues:

 - Fixes #565

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

### CODE REVIEW

File: internal/pkg/cgroups/manager_linux_test.go [hunk 1]
```diff
@@ -134,31 +135,49 @@ func ensureContainsInt(t *testing.T, path string, wantInt int64) {
...
-			f := strings.Fields(scanner.Text())
-			if len(f) < 2 {
-				t.Errorf("Could not check process state - not enough fields: %s", scanner.Text())
+	for r := 0; r <= retries; r++ {
+		if r > 0 {
+			t.Logf("Process %d has state %q, need %q - retrying %d/%d", pid, procState, wantStates, r, retries)
+			time.Sleep(delay)
+		}
+
+		if _, err := file.Seek(0, 0); err != nil {
```
Comment (tri-adam) [inline internal/pkg/cgroups/manager_linux_test.go:158]: Nit: clearer if you use a `const` for the whence:

```suggestion
		if _, err := file.Seek(0, io.SeekStart); err != nil {
```

**Review by tri-adam — APPROVED** [review]
LGTM, just one small suggestion.
