### PR TITLE
fix: avoid duplicate `remote.yaml` entries from multiple login

### LINKED ISSUE #214: Duplicate remote login to OCI URIs creates multiple entries in remote.yaml
**Version of Singularity**
3.8.1

**Describe the bug**
If you `singularity remote login docker://docker.io` twice, two entries for `docker.io` are created in the `remote.yaml`, which is incorrect.

The actual auth token in `~/.singularity/docker-config.json` is replaced, rather than duplicated, which is correct.

A subsequent `singularity remote logout docker://docker.io` leaves a phantom `remote.yaml` entry, with no associated entry in `~/.singularity/docker-config.json`. Additionally, attempting to remove it by `logout` again will fail with `FATAL:   while verifying token: not logged in`

**To Reproduce**

```
singularity remote login --username xxx docker://docker.io
singularity remote login --username xxx docker://docker.io
singularity remote logout docker://docker.io
singularity remote list
```

### LINKED ISSUE #222: e2e remote test failing after #217
**Version of Singularity**

master

**Describe the bug**

#217 changed usage strings on the remote sub-commands, without me realizing they were checked in the e2e tests. Since no e2e test code or go.mod modifications were made, the e2e tests were not triggered in CI. They are now failing in PRs in which they are triggered.

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

Repeated `remote login` with the same URI can cause duplicate
`Credentials` entries in `~/remote.yaml`.

Ensure a `remote login` with an existing configured URI replaces the
existing entry. Make `remote logout` remove all entries to clean up the
result of this bug.

Also has a commit to correct e2e test looking for usage messages that were changed in #217 - but e2e was not triggered there.

### This fixes or addresses the following GitHub issues:

 - Fixes #214 
 - Fixes #222 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

### CODE REVIEW

File: internal/pkg/remote/remote.go [hunk 1]
```diff
@@ -266,13 +278,16 @@ func (c *Config) Logout(uri string) error {
...
+	for i := 0; i < len(c.Credentials); i++ {
+		cred := c.Credentials[i]
 		if remoteutil.SameURI(cred.URI, uri) {
 			c.Credentials = append(c.Credentials[:i], c.Credentials[i+1:]...)
-			return nil
+			i = -1
 		}
 	}
-	return fmt.Errorf("%s is not configured", uri)
+	return nil
```
Comment (dtrudg) [inline internal/pkg/remote/remote.go:290]: Note - the `%s not configured` error was redundant here. If `credential.Manager.Logout` succeeds in logging out of something then it's not an error to not remove an entry from `remote.yaml`... We may have successfully cleaned up a mismatch from `remote.yaml` -> `docker-config.json`

**Review by EmmEff — APPROVED** [review]
