### PR TITLE
e2e: look for mkfs.ext3 using FindBin()

### LINKED ISSUE #2078: sles15: OCI image bind tests failing
**Version of Singularity**

main

**Describe the bug**

```
    --- FAIL: TestE2E (477.12s)
        --- FAIL: TestE2E/PAR (0.00s)
            --- FAIL: TestE2E/PAR/ACTIONS (0.02s)
                --- FAIL: TestE2E/PAR/ACTIONS/ociBindImage (0.05s)
                --- FAIL: TestE2E/PAR/ACTIONS/bind_image (0.05s)
                --- FAIL: TestE2E/PAR/ACTIONS/persistent_overlay (0.06s)
```

I believe that this is just down to `mkfs.ext3` not being on the default PATH.... under [/usr]/sbin and [/usr]/sbin isn't on PATH?

```
    === CONT  TestE2E/PAR/ACTIONS/persistent_overlay
        exec.go:28: Running cmd "mksquashfs" with args ["/tmp/stest.1039513117/persistent-overlay-2403508318/root-squash-dir-238268924" "/tmp/stest.1039513117/persistent-overlay-2403508318/squashfs.simg" "-noappend" "-all-root"]
        exec.go:28: Running cmd "dd" with args ["if=/dev/zero" "of=/tmp/stest.1039513117/persistent-overlay-2403508318/ext3_fs.img" "bs=1M" "count=64" "status=none"]
        exec.go:28: Running cmd "mkfs.ext3" with args ["-q" "-F" "/tmp/stest.1039513117/persistent-overlay-2403508318/ext3_fs.img"]
        actions.go:789: Unexpected error while running command.
  
            Command:  mkfs.ext3 -q -F /tmp/stest.1039513117/persistent-overlay-2403508318/ext3_fs.img
            ExitCode: 127
            Error:    exec: "mkfs.ext3": executable file not found in $PATH
            Stdout:
            Stderr:
```

### PR DESCRIPTION
**Pull request by preminger**
## Description of the Pull Request (PR):

Use bin.FindBin() to locate the `mkfs.ext3` command in e2e tests.

### This fixes or addresses the following GitHub issues:

 - Fixes #2078

### CODE REVIEW

File: e2e/actions/actions.go [hunk 1]
```diff
@@ -784,7 +785,11 @@ func (c actionTests) PersistentOverlay(t *testing.T) {
 		t.Fatalf("Unexpected error while running command.\n%s", res)
 	}
 
-	cmd = exec.Command("mkfs.ext3", "-q", "-F", ext3Img)
+	mkfsExt3Cmd, err := bin.FindBin("mkfs.ext3")
+	if err != nil {
+		t.Fatal("Unable to find 'mkfs.ext3' binary even though require.Command() was called")
```
Comment (tri-adam) [inline e2e/actions/actions.go:790]: Probably worth outputting the error to aid troubleshooting (here and the other three similar spots)?
```suggestion
		t.Fatalf("Unable to find 'mkfs.ext3' binary even though require.Command() was called: %v", err)
```

**Review by tri-adam — APPROVED** [review]
One suggestion, LGTM otherwise!
